## 2-4_Creating_binary_features_through_thresholding

In [1]:
## 1. Load the Boston dataset and set up the explanatory and target variables.

import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

X = housing.data
y = housing.target.reshape(-1, 1)

print(X.shape)
print(y.shape)

(20640, 8)
(20640, 1)


In [2]:
## 2. Binarize the target variable using the mean value as the threshold.

from sklearn import preprocessing

new_target = preprocessing.binarize(
    y,
    threshold=y.mean()
)

new_target[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [3]:
## 3. Confirm the binary conversion directly using a NumPy comparison.

(y[:5] > y.mean()).astype(int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [4]:
## 4. Create a Binarizer using the mean target value as the threshold and transform the target variable.

binar = preprocessing.Binarizer(threshold=y.mean())

new_target = binar.fit_transform(y)

new_target[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [5]:
## 4. Create a Binarizer using the mean target value as the threshold and transform the target variable.

binar = preprocessing.Binarizer(threshold=y.mean())

new_target = binar.fit_transform(y)

new_target[:5]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [6]:
## 5. Confirm that a sparse matrix cannot be binarized using a negative threshold.

from scipy.sparse import coo

spar = coo.coo_matrix(np.random.binomial(1, 0.25, 100))

preprocessing.binarize(spar, threshold=-1)

C:\Users\toshi\AppData\Local\Temp\ipykernel_8960\2844065446.py:5: DeprecationWarning: Please import `coo_matrix` from the `scipy.sparse` namespace; the `scipy.sparse.coo` namespace is deprecated and will be removed in SciPy 2.0.0.
  spar = coo.coo_matrix(np.random.binomial(1, 0.25, 100))


ValueError: Cannot binarize a sparse matrix with threshold < 0