## 2-6_Imputing_missing_values_through_various_strategies

In [2]:
## 1. Load the Iris dataset and randomly introduce missing values.

from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
iris_X = iris.data

masking_array = np.random.binomial(
    1,
    0.25,
    iris_X.shape
).astype(bool)

iris_X[masking_array] = np.nan

In [3]:
## 2. Display the first five rows of the missing-value mask.

masking_array[:5]

array([[False,  True,  True, False],
       [False, False,  True, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False,  True,  True,  True]])

In [4]:
## 3. Display the first five rows of the Iris dataset containing missing values.

iris_X[:5]

array([[5.1, nan, nan, 0.2],
       [4.9, 3. , nan, 0.2],
       [nan, nan, 1.3, 0.2],
       [nan, 3.1, 1.5, 0.2],
       [5. , nan, nan, nan]])

In [5]:
## 4. Impute missing values using the mean of each feature.

from sklearn.impute import SimpleImputer

impute = SimpleImputer(strategy="mean")

iris_X_prime = impute.fit_transform(iris_X)

iris_X_prime[:5]

array([[5.1       , 3.01891892, 3.72410714, 0.2       ],
       [4.9       , 3.        , 3.72410714, 0.2       ],
       [5.92991453, 3.01891892, 1.3       , 0.2       ],
       [5.92991453, 3.1       , 1.5       , 0.2       ],
       [5.        , 3.01891892, 3.72410714, 1.25950413]])

In [6]:
## 5. Display a value that was imputed with the mean.

iris_X_prime[0, 0]

np.float64(5.1)

In [7]:
## 6. Display the original value before imputation for comparison.

iris_X[0, 0]

np.float64(5.1)

In [8]:
## 7. Impute missing values using the median of each feature.

from sklearn.impute import SimpleImputer

impute = SimpleImputer(strategy="median")

iris_X_prime = impute.fit_transform(iris_X)

iris_X_prime[:5]

array([[5.1 , 3.  , 4.35, 0.2 ],
       [4.9 , 3.  , 4.35, 0.2 ],
       [5.9 , 3.  , 1.3 , 0.2 ],
       [5.9 , 3.1 , 1.5 , 0.2 ],
       [5.  , 3.  , 4.35, 1.4 ]])

In [9]:
## 8. Replace all missing values with a constant value of -1.

iris_X[np.isnan(iris_X)] = -1

iris_X[:5]

array([[ 5.1, -1. , -1. ,  0.2],
       [ 4.9,  3. , -1. ,  0.2],
       [-1. , -1. ,  1.3,  0.2],
       [-1. ,  3.1,  1.5,  0.2],
       [ 5. , -1. , -1. , -1. ]])

In [10]:
## 9. Treat -1 as a missing value and impute it using the mean of each feature.

from sklearn.impute import SimpleImputer

impute = SimpleImputer(
    missing_values=-1,
    strategy="mean"
)

iris_X_prime = impute.fit_transform(iris_X)

iris_X_prime[:5]

array([[5.1       , 3.01891892, 3.72410714, 0.2       ],
       [4.9       , 3.        , 3.72410714, 0.2       ],
       [5.92991453, 3.01891892, 1.3       , 0.2       ],
       [5.92991453, 3.1       , 1.5       , 0.2       ],
       [5.        , 3.01891892, 3.72410714, 1.25950413]])

In [11]:
## 10. Replace missing values with -1 using pandas and NumPy.

import pandas as pd

iris_X_prime = np.where(
    pd.DataFrame(iris_X).isnull(),
    -1,
    iris_X
)

iris_X_prime[:5]

array([[ 5.1, -1. , -1. ,  0.2],
       [ 4.9,  3. , -1. ,  0.2],
       [-1. , -1. ,  1.3,  0.2],
       [-1. ,  3.1,  1.5,  0.2],
       [ 5. , -1. , -1. , -1. ]])

In [12]:
## 11. Replace missing values with -1 using the pandas fillna method.

pd.DataFrame(iris_X).fillna(-1)[:5].values

array([[ 5.1, -1. , -1. ,  0.2],
       [ 4.9,  3. , -1. ,  0.2],
       [-1. , -1. ,  1.3,  0.2],
       [-1. ,  3.1,  1.5,  0.2],
       [ 5. , -1. , -1. , -1. ]])