## 2-8_Putting_it_all_together_with_Pipelines

In [1]:
## 1. Load the Iris dataset and randomly introduce missing values.

from sklearn.datasets import load_iris
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
iris_data = iris.data

mask = np.random.binomial(
    1,
    .25,
    iris_data.shape
).astype(bool)

iris_data[mask] = np.nan

iris_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, nan, 1.4, nan],
       [4.7, 3.2, 1.3, 0.2],
       [nan, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, nan]])

In [2]:
## 2. Build a pipeline that imputes missing values and applies PCA.

from sklearn import pipeline, preprocessing, decomposition
from sklearn.impute import SimpleImputer


pca = decomposition.PCA()
imputer = SimpleImputer()


pipe = pipeline.Pipeline([
    ('imputer', imputer),
    ('pca', pca)
])

iris_data_transformed = pipe.fit_transform(iris_data)

iris_data_transformed[:5]

array([[-2.62186641, -0.00682068, -0.1999654 ,  0.23534602],
       [-2.32414475, -0.25591019,  0.80246459, -0.06989012],
       [-2.80363086, -0.42130437, -0.10230964,  0.02173817],
       [-2.27436836,  0.59342845, -0.30183296, -0.31152761],
       [-2.33728595, -0.03032178,  0.75674144,  0.42935643]])

In [3]:
## 3. Create the same pipeline using make_pipeline and inspect its steps.

pipe2 = pipeline.make_pipeline(imputer, pca)

pipe2.steps

[('simpleimputer', SimpleImputer()), ('pca', PCA())]

In [4]:
## 4. Transform the Iris dataset using the pipeline created with make_pipeline.

iris_data_transformed2 = pipe2.fit_transform(iris_data)

iris_data_transformed2[:5]

array([[-2.62186641, -0.00682068, -0.1999654 ,  0.23534602],
       [-2.32414475, -0.25591019,  0.80246459, -0.06989012],
       [-2.80363086, -0.42130437, -0.10230964,  0.02173817],
       [-2.27436836,  0.59342845, -0.30183296, -0.31152761],
       [-2.33728595, -0.03032178,  0.75674144,  0.42935643]])

In [5]:
## 5. Set the number of PCA components to two through the pipeline.

pipe2.set_params(pca__n_components=2)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('simpleimputer', ...), ('pca', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'mean'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a 

In [6]:
## 6. Transform the Iris dataset into two principal components.

iris_data_transformed3 = pipe2.fit_transform(iris_data)

iris_data_transformed3[:5]

array([[-2.62186641, -0.00682068],
       [-2.32414475, -0.25591019],
       [-2.80363086, -0.42130437],
       [-2.27436836,  0.59342845],
       [-2.33728595, -0.03032178]])