## 01_NumpyBasics

### NumpPy配列の形状と次元

In [4]:
## Importing the numpy library
import numpy as np

In [5]:
## This generates a Numpy array containing 10 numbers. It's equivalent to Python's range(10) method.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Store this array in a variable and view its shape using `shape`.
array_1 = np.arange(10)
array_1.shape

(10,)

In [7]:
#Get the number of dimensions of array_1
array_1.ndim

1

In [8]:
# This array contains 10 elements.
# Let's try changing the shape of the array by calling the reshape method.
array_1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# The array's structure has been changed to a 5x2 data object.
# Save this modified array.
array_1 = array_1.reshape((5,2))

In [11]:

# Let's re-examine the dimensions of array_1.
# Note that it's now 2 dimensions.
array_1.ndim 

2

### NumPyのブロードキャスト

In [12]:
# Use broadcasting to add 1 to each element of each array.
# Note that changes to the array will not be saved.
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
# Create a new array called array_2.
# Multiply this array by itself.
# All elements have been squared.

array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
# Note that this is equivalent to array_2 * array_2
array_2 = array_2 ** 2  
array_2 = array_2.reshape((5,2))
array_2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [16]:
# Let's try changing array_1 as well.
array_1 = array_1 + 1
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
# Let's try adding array_1 and array_2 elements together.
array_1 + array_2

array([[ 1,  3],
       [ 7, 13],
       [21, 31],
       [43, 57],
       [73, 91]])

### NuPyの初期化とdtype

In [ ]:
# Use np.zeros to initialize the array with zeros.
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
# Use `np.ones` to initialize an array with 1s.
# Adding the `dtype` parameter and setting it to `np.int64` makes the value 1 a NumPy integer type.
# `dtype` represents the type of all elements in a NumPy array.
# The elements of an array remain the same while the array is being used.
np.ones((5,2), dtype = np.int64)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [30]:
# Use `np.empty` to allocate memory for an array of a specified size and dtype, 
# but without initializing the elements with specific values.
np.empty((5,2), dtype = float)

array([[2.17388884e-322, 6.40275276e-315],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.11253693e-308]])