## 1_2_NumpyBasics

### Numpy array shape and dimensions

In [1]:
## 1. Importing the numpy library
import numpy as np

In [2]:
## 2. This generates a Numpy array containing 10 numbers. It's equivalent to Python's range(10) method.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
## 3. Store this array in a variable and view its shape using `shape`.
array_1 = np.arange(10)
array_1.shape

(10,)

In [4]:
## 4. Get the number of dimensions of array_1
array_1.ndim

1

In [5]:
## 5. This array contains 10 elements.
## Let's try changing the shape of the array by calling the reshape method.
array_1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
## 6. The array's structure has been changed to a 5x2 data object.
## Save this modified array.
array_1 = array_1.reshape((5,2))

In [7]:

## 7. Let's re-examine the dimensions of array_1.
## Note that it's now 2 dimensions.
array_1.ndim 

2

### NumPy broadcasting

In [8]:
## 8. Use broadcasting to add 1 to each element of each array.
## Note that changes to the array will not be saved.
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
## 9. Create a new array called array_2.
## Multiply this array by itself.
## All elements have been squared.

array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
## 10. Note that this is equivalent to array_2 * array_2
array_2 = array_2 ** 2  
array_2 = array_2.reshape((5,2))
array_2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [11]:
## 11. Let's try changing array_1 as well.
array_1 = array_1 + 1
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
## 12. Let's try adding array_1 and array_2 elements together.
array_1 + array_2

array([[ 1,  3],
       [ 7, 13],
       [21, 31],
       [43, 57],
       [73, 91]])

### NumPy initialization and dtype

In [13]:
## 14. Use np.zeros to initialize the array with zeros.
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
## 15. Use `np.ones` to initialize an array with 1s.
## Adding the `dtype` parameter and setting it to `np.int64` makes the value 1 a NumPy integer type.
## `dtype` represents the type of all elements in a NumPy array.
## The elements of an array remain the same while the array is being used.
np.ones((5,2), dtype = np.int64)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [15]:
## 16. Use `np.empty` to allocate memory for an array of a specified size and dtype, 
## but without initializing the elements with specific values.
np.empty((5,2), dtype = float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### INDEX

In [17]:
## 17. Access the element at the first row and first column of array_1.
array_1[0,0]    #Finds value in first row and first column.

np.int64(1)

In [19]:
## 18. Display the first line.
array_1[0,:]

array([1, 2])

In [22]:
## 19. Display the first column.
array_1[:,0]

array([1, 3, 5, 7, 9])

In [23]:
## 20. Display the values ​​for both axes (rows and columns) from row 3 to row 5.
array_1[2:5, :]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
## 21. Display only the values ​​in the first column from rows 3 to 5.
array_1[2:5,0]

array([5, 7, 9])

### Boolean array
Furthermore, NumPy handles indices as Boolean values ​​(logical values).

In [26]:
## 22. First, create a Boolean array from array_1.
array_1 > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [27]:
## 23. To filter using an array of Boolean values, enclose the array of Boolean values ​​in square brackets ([]).
array_1[array_1 > 5]

array([ 6,  7,  8,  9, 10])

### Arithmetic operations

In [29]:
## 24. Use the sum method to sum up all elements of array_1.
array_1.sum()

np.int64(55)

In [30]:
## 25. Calculate the sum for each row.
array_1.sum(axis = 1)

array([ 3,  7, 11, 15, 19])

In [31]:
## 26. Calculate the sum for each column.
array_1.sum(axis = 0)

array([25, 30])

In [32]:
## 27. Similarly, we find the mean of each column. Note that the dtype of the array mean is np.float.
array_1.mean(axis = 0)

array([5., 6.])

### NaN値

In [38]:
## 28. scikit-learn does not accept np.nan values. Therefore, we create array_3 as follows:
array_3 = np.array([np.nan, 0, 1, 2, np.nan])


In [39]:
## 29. To search for NaN values, use a special Boolean array created by the np.isnan function
##  (True represents NaN values).
np.isnan(array_3)

array([ True, False, False, False,  True])

In [40]:
## 30. To exclude NaN values, use the tilde symbol (~) to perform a logical negation of the elements in this Boolean array. 
## When doing so, enclose the negation expression in square brackets ([]).
array_3[~np.isnan(array_3)]

array([0., 1., 2.])

In [41]:
## 31. Alternatively, set the NaN value to 0.
array_3[np.isnan(array_3)] = 0
array_3

array([0., 0., 1., 2., 0.])