## 3-5_Using_truncated_SVD_to_reduce_dimensionality

In [1]:
## 1. Load the Iris dataset and set the explanatory and target variables.

from sklearn.datasets import load_iris
iris = load_iris()
iris_X = iris.data
y = iris.target

In [2]:
## 2. Reduce the Iris dataset to two dimensions using Truncated SVD.

from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(2)
iris_transformed = svd.fit_transform(iris_X)

In [3]:
## 3. Display the explained variance ratio of the two components.

svd.explained_variance_ratio_

array([0.52875361, 0.44845576])

In [4]:
## 4. Create a small matrix for demonstrating singular value decomposition.

from scipy.linalg import svd
import numpy as np
D = np.array([[1, 2], [1, 3], [1, 4]])
D

array([[1, 2],
       [1, 3],
       [1, 4]])

In [5]:
## 5. Perform singular value decomposition and display the shapes of the resulting matrices.

U, S, V = svd(D, full_matrices=False)
U.shape, S.shape, V.shape

((3, 2), (2,), (2, 2))

In [6]:
## 6. Reconstruct the original matrix from the SVD components.

np.dot(U.dot(np.diag(S)), V)

array([[1., 2.],
       [1., 3.],
       [1., 4.]])